# Generated by Django 5.1.7 on 2025-03-19 20:18

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[board.models.validate_price]),
        ),
    ]
