# Generated by Django 5.1.7 on 2025-04-28 17:57

from django.db import migrations
import json

from typing import Any


def create_log_user_count(apps: Any, schema_editor: Any) -> None:
    """
    Creates a periodic task that logs the total number of users
    in the database every 10 minutes.
    :param apps: The registry of all installed apps. Used to get historical models.
    :param schema_editor: Schema editor for database operations during migration.
    :return:
    """
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute='*/10',
        hour='*',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    PeriodicTask.objects.get_or_create(
        crontab=schedule,
        name='Log User Count Crontab',
        task='board.tasks.log_user_count',
        defaults={
            'args': json.dumps([]),
            'kwargs': json.dumps({}),
            'enabled': True,
        }
    )


class Migration(migrations.Migration):
    """
    Django migration to create a periodic task for logging user count.
    """

    dependencies = [
        ('board', '0004_ad_image'),
    ]

    operations = [
        migrations.RunPython(create_log_user_count),
    ]
